loginButton = "xpath://input[@id='login-button']"
userNameTextBox = "id:user-name"
passwordTextBox = "id:password"
header = "xpath://div[@class='login_logo']"
appLogoSelector = "xpath://div[@class='app_logo']"
